name: slm-scratch-experiment
channels:
  - default
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - python=3.8.5
  - pytest=6.1.2
  - pandas=1.4.1
  - numpy=1.22.2
  - requests=2.25.0
  - scikit-learn=0.24.2
  - dill=0.3.4
  # - tqdm=4.64.0
  - ruamel.yaml=0.17.19
  - yappi=1.3.3
  - pillow= 9.0.1
  - jupyterlab=3.2.9
  - jupyterlab_widgets
  - jupyterlab_code_formatter
  - jupyter=1.0.0
  - ipywidgets=7.7.0
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - plotly=5.9.0
  - pandas-profiling=3.1.0
  - black=22.3.0
  - minio=7.1.1
  - pip
  - pip:
      - tensorflow==2.9.0
      - tensorflow-hub==0.12.0
      - adabelief-tf==0.2.0
      - tensorflow-addons==0.17.1
      - focal-loss==0.0.7
      - pydot==1.4.2
      - graphviz==0.20
      - opencv-python-headless==4.5.5.62
      - opencv-contrib-python-headless==4.5.5.62
      - imbalanced-learn==0.9.1
