name: "model_3_328mb"
backend: "tensorflow"
platform: "tensorflow_savedmodel"
max_batch_size: 64
input [
  {
    name: "random_flip_input"
    data_type: TYPE_FP32
    dims: [ 256, 256, 1 ]
  }
]
output [
  {
    name: "dense_4"
    data_type: TYPE_FP32
    dims: [ 2 ]
  }
]
